server {
    listen 80;
    server_name arogya-mobile-clinic.me;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name arogya-mobile-clinic.me;

    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /users { proxy_pass http://user-service:8081; }
    location /roles { proxy_pass http://user-service:8081; }
    location /patient_profile { proxy_pass http://user-service:8081; }
    location /doctor_profile { proxy_pass http://user-service:8081; }
    location /admin_profile { proxy_pass http://user-service:8081; }
    location /technician_profile { proxy_pass http://user-service:8081; }
    
    location /clinics { proxy_pass http://clinic-service:8082; }
    location /clinic_doctors { proxy_pass http://clinic-service:8082; }
    
    location /queue { proxy_pass http://queue-service:8085; }
    
    location /consultations { proxy_pass http://consultation-service:8086; }
    location /lab-tests { proxy_pass http://consultation-service:8086; }
    
    location /test-results { proxy_pass http://medical-records-service:8087; }
    
    location /chat { proxy_pass http://arogya-chatbot:8091; }
    location /health { proxy_pass http://arogya-chatbot:8091; }
}
