server {
    listen 80;
    server_name arogya-mobile-clinic.me;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name arogya-mobile-clinic.me;

    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /users { proxy_pass http://api-gateway:8090; }
    location /roles { proxy_pass http://api-gateway:8090; }
    location /patient_profile { proxy_pass http://api-gateway:8090; }
    location /doctor_profile { proxy_pass http://api-gateway:8090; }
    location /admin_profile { proxy_pass http://api-gateway:8090; }
    location /technician_profile { proxy_pass http://api-gateway:8090; }
    
    location /clinics { proxy_pass http://api-gateway:8090; }
    location /clinic_doctors { proxy_pass http://api-gateway:8090; }
    
    location /queue { proxy_pass http://api-gateway:8090; }
    
    location /consultations { proxy_pass http://api-gateway:8090; }
    location /lab-tests { proxy_pass http://api-gateway:8090; }
    
    location /test-results { proxy_pass http://api-gateway:8090; }
    
    location /chat { 
        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_pass http://arogya-chatbot:8091; 
    }
    location /health { proxy_pass http://arogya-chatbot:8091; }
}
